catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowedbooks/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('authors/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('authors/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('authors/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete')
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls'))
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre')
    
    def __str__(self):
        return self.name
    
class Book(models.Model):
    title = models.CharField(max_length=200)
    
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    
    genre = models.ManyToManyField(Genre, help_text='Select a genre of book')
    
    class Meta:
        ordering = ['title']
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])
    
    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'
    
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )
    
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text="Book availability"
    )
    
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)
    
    def __str__(self):
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        else:
            return False
    
class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length = 100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    class Meta:
        ordering = ['last_name', 'first_name']
        
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'
    
class Language(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from .models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
    
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
            
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
        return data
    
class RenewBookModelForm(ModelForm):
    
    def clean_due_back(self):
        data = self.cleaned_data['due_back']
        
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
            
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
        return data
    
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renwal date')}
        help_textx = {'due_back': _('Enter a date between now and 4 weeks (default: 3).')}
    

catalog/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from .models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import RenewBookForm
# Create your views here.

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    num_authors = Author.objects.count()
    
    num_genres = Genre.objects.count()
    
    num_fablehaven = Book.objects.filter(title__contains='Fablehaven').count()
    
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1
    
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_fablehaven': num_fablehaven,
        'num_visits': num_visits
    }

    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = 2
    


class BookDetailView(generic.DetailView):
    model = Book
    
class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10
    
class AuthorDetailView(generic.DetailView):
    model = Author
    
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    
class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')
    
@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    
    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            
            return HttpResponseRedirect(reverse('all-borrowed'))
        
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
    
    context = {
        'form': form,
        'book_instance': book_instance
    }
    
    return render(request, 'catalog/book_renewal_librarian.html', context)


class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}
    
class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__'

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

catalog/templates/catalog/author_confirm_delete.html
{%extends "base_generic.html"%}

{%block content%}
    <h1>Delete Author</h1>
    <p>Are you sure you want to delete the author: {{author}}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type='submit' value='Yes, delete.'>
    </form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{%extends "base_generic.html"%}
{%block title%}
    <title>{{author.last_name}}, {{author.first_name}}</title>
{%endblock%}

{%block content%}
    <h1>{{author.last_name}}, {{author.first_name}}</h1>
    <p><strong>DOB:</strong> {{author.date_of_birth}}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Books</h4>
        
        {% for book in author.book_set.all %}
            <hr>
            <p><strong>Title:</strong> {{book.title}}</p>
            <p><strong>Summary:</strong> {{book.summary}}</p>
            <p><strong>Genre: </strong> {{book.genre.all|join:","}}</p>
            <p><strong>ISBN: </strong> {{book.isbn}} </p>
        {%endfor%}
    </div>

{%endblock%}

catalog/templates/catalog/author_form.html
{%extends "base_generic.html"%}

{% block content %}
    <form action="" method="">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}


{%block title%}
    <title>Authors</title>
{%endblock%}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
    <ul>
        {% for author in author_list %}
            <li>
                <a href='{{ author.get_absolute_url}}'>{{author.last_name}}, {{author.first_name}}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{%extends "base_generic.html"%}
{%block title%}
    <title>{{book.title}}</title>
{%endblock%}

{%block content%}
    <h1>Title: {{ book.title }}</h1>
    <p><strong>Author:</strong> <a href="book.author.get_absolute_url">{{ book.author }} </a></p>
    <p><strong>Summary:</strong> {{book.summary}} </p>
    <p><strong>ISBN: </strong> {{book.isbn}} </p>
    <p><strong>Genre: </strong> {{book.genre.all|join:","}}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>
        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a'%}text-success{% elif copy.status == 'm' %}text-danger{%else%}text-warning{%endif%}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
            {%endif%}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p><strong>Language:</strong> {{copy.language}}</p>
            <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
        {%endfor%}
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}


{%block title%}
    <title>Books</title>
{%endblock%}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
            <li>
                <a href='{{ book.get_absolute_url}}'>{{book.title}}</a> ({{book.author}})
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renewal_librarian.html
{% extends 'base_generic.html'%}

{%block title%}<title>Renew</title>{%endblock%}

{%block content%}
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>

    <p{% if book_instance.is_overdue %} class='text-danger'{% endif %} >Due date: {{book_instance.due_back }}</p>

    <form action='' method='post'>
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type='submit' value='Submit'>
    </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}
{% block title %}<title>Borrowed Books</title>{% endblock %}

{%block content%}
    <h1>Borrowed books</h1>
    
    {% if bookinstance_list %}
    <ul>
        {%for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{%endif%}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{bookinst.due_back}}) -{{bookinst.borrower}}
            {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
        </li>
        {%endfor%}
    </ul>

    {% else %}
        <p>There are no borrowed books</p>
    {% endif %}
{%endblock%}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% block title %}<title>My Books</title>{% endblock %}

{%block content%}
    <h1>Borrowed books</h1>
    
    {% if bookinstance_list %}
    <ul>
        {%for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{%endif%}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{bookinst.due_back}})
        </li>
        {%endfor%}
    </ul>

    {% else %}
        <p>There are no borrowed books</p>
    {% endif %}
{%endblock%}